# 텐서플로우의 사용법을 이해해보자,

In [1]:
import numpy as np
import tensorflow as tf

print(tf.__version__)

2.0.0-rc1


일반 배열, 넘파이 배열 그리고 텐서의 차이

In [2]:
a = [1,2,3]
type(a)

list

In [4]:
b = np.array(a)
type(b)

numpy.ndarray

__Tensor 생성__

list 를 tensor 에 담기 위해선 tf.constant 함수를 사용해야 한다.

In [5]:
c = tf.constant(a)
type(c)

tensorflow.python.framework.ops.EagerTensor

In [6]:
c

<tf.Tensor: id=0, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [8]:
# 튜플 형태도 담을 수 있다.
tf.constant(((1,2,3),(4,5,6)))

<tf.Tensor: id=1, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [23]:
# np.arr Arrray 들도 담을 수 있다.
arr = np.array([1,2,3])
tensor = tf.constant(arr)
tensor

(<tf.Tensor: id=12, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>,
 dtype('int32'))

### Tensor에 담긴 정보를 확인 하기 

In [12]:
tensor.shape

TensorShape([3])

In [14]:
tensor.dtype

tf.int32

In [20]:
# data type 변환
tensor =  tf.constant([1,2,3], dtype=tf.float32)
tensor

<tf.Tensor: id=10, shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [21]:
# numpy 에서는 astype 을 이용하여 data type을 변경한다. 
arr = np.array([1,2,3], dtype=np.float32)
arr.dtype

dtype('float32')

In [24]:
arr.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

In [25]:
# 텐서플로우에서는 tf.cast를 사용합니다
tf.cast(tensor, dtype=tf.uint8)

<tf.Tensor: id=13, shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

In [27]:
# Tensor에서 numpy 불러오기
tensor.numpy()

array([1, 2, 3])

In [28]:
# 또는 
np.array(tensor)

array([1, 2, 3])

### 난수 생성

tensorflow 에는 normal Distribution 과   
Uniform Distribution 두가지가 존재한다.

- Normal Distribution 은 중심극한 이론에 의한 연속적인 모양

- Uniform Distribution은 중심극한 이론과는 무관하며 불연속적이며 일정한 분포

In [29]:
# numpy 에서는 normal distribution을 기본적으로 생성
np.random.randn(9)

array([ 0.90096486,  0.02903516, -0.83256224,  0.37682231, -0.34592802,
        0.4940209 , -0.0408395 ,  1.71699832,  1.72622002])

In [33]:
tf.random.normal([3,3])

<tf.Tensor: id=31, shape=(3, 3), dtype=float32, numpy=
array([[-0.5931361 , -0.66766864, -1.0263194 ],
       [ 1.8666781 , -0.23585942,  1.3552066 ],
       [ 0.70944   ,  0.9722929 , -1.115248  ]], dtype=float32)>

In [34]:
tf.random.uniform([3,3])

<tf.Tensor: id=38, shape=(3, 3), dtype=float32, numpy=
array([[0.8007091 , 0.8860134 , 0.99920714],
       [0.48785627, 0.38376975, 0.08157063],
       [0.55748475, 0.09109092, 0.47648525]], dtype=float32)>